{{- if .Values.rollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else -}}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: "airone"
  labels:
    {{- include "airone.labels" . | nindent 4 }}
    app.kubernetes.io/component: airone
spec:
{{- if .Values.rollout.enabled }}
  strategy:
    blueGreen:
      previewService: airone-preview
      activeService: airone
      autoPromotionEnabled: false
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}
{{- end }}
  replicas: 1
  selector:
    matchLabels:
      app: airone
  template:
    metadata:
      labels:
        app: airone
    spec:
      containers:
        - name: airone
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
          {{- include "airone.env" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: mysecret
          command: ["/bin/sh"]
          args: ["-c", ". /config/dynamicenv.sh && /docker-entrypoint.sh gunicorn"]
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "airone.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
