apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-celery"
  labels:
    {{- include "airone.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- include "airone.env" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: mysecret
          command: ["/bin/sh"]
          args: ["-c", ". /config/dynamicenv.sh && /app/scripts/docker-entrypoint celery"]
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "airone.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
