apiVersion: batch/v1
kind: Job
metadata:
  name: create-vhost
  labels:
    {{- include "airone.labels" . | nindent 4 }}
    app.kubernetes.io/component: deploy
  annotations:
    # This is what defines this resource as a hook.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: create-vhost
      labels:
        {{- include "airone.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: create-vhost
          image: docker.io/bitnami/rabbitmq
          env:
          {{- include "airone.env" . | nindent 12 }}
          command: ["/bin/bash", "/config/create_vhost.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: airone-config
