apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-install"
  labels:
    {{- include "airone.labels" . | nindent 4 }}
    app.kubernetes.io/component: install
  annotations:
    # This is what defines this resource as a hook.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "airone.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: init-createdb
          image: mysql/mysql-operator
          command: [
            "mysqlsh",
            "--sql",
            "--host=airone-instances",
            "--user=airone",
            "--password=password",
            "--passwords-from-stdin",
            "--execute=CREATE DATABASE IF NOT EXISTS airone"
          ]
      containers:
        - name: airone-install
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- include "airone.env" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: mysecret
          command: ["/bin/bash", "/config/install.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ include "airone.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
