apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    {{- include "airone.labels" . | nindent 4 }}
stringData:
  AIRONE_RABBITMQ_URL: "amqp://airone:password@{{ .Release.Name }}-rabbitmq/"
  AIRONE_ELASTICSEARCH_NODES: "elasticsearch-master:9200"
