{{- if not .Values.airone.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: airone-secret
  labels:
    {{- include "airone.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $null := required "A value for one of the following variables is required: airone.secretKey (secure random value), airone.existingSecret (secret name)" (or .Values.airone.secretKey .Values.airone.existingSecret) }}
  secretKey: {{ default "" .Values.airone.secretKey | b64enc | quote }}
  ssoPrivateKey: {{ default "" .Values.airone.sso.privateKey | b64enc | quote }}
  ssoEntityId: {{ default "" .Values.airone.sso.entityId | b64enc | quote }}
  ssoX509Cert: {{ default "" .Values.airone.sso.x509Cert | b64enc | quote }}
  emailPassword: {{ default "" .Values.airone.email.password | b64enc | quote }}
  mysqlPassword: {{ default "" .Values.externalMySQL.password | b64enc | quote }}
  elasticsearchPassword: {{ default "" .Values.externalElasticsearch.password | b64enc | quote }}
  rabbitmqPassword: {{ default "" .Values.externalRabbitmq.password | b64enc | quote }}
{{- end -}}