{{- if .Values.rollout.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: airone-preview
  labels:
    {{- include "airone.labels" . | nindent 4 }}
spec:
  selector:
    app: airone
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "1.1.1.1/32"

---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: airone
  labels:
    {{- include "airone.labels" . | nindent 4 }}
spec:
  selector:
    app: airone
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - "111.108.92.6/32"
