{{- if .Values.rollout.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: airone-preview
  labels:
    {{- include "airone.labels" . | nindent 4 }}
spec:
  selector:
    app: airone
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: airone
  labels:
    {{- include "airone.labels" . | nindent 4 }}
spec:
  selector:
    app: airone
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
