apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-directory
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.storageClass }}
